config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts,  except: :destroy do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :users

  resources :categories, only: [:new, :create, :show]

end

app/models/post.rb
class Post   < ActiveRecord::Base

  include VoteableFerSept, SlugFerGem

  BADWORDS =  ['bad', 'words']

  #belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :user
  has_many :comments
  has_many :categories, through: :post_categories
  has_many :post_categories

  validates :title, presence: true

  # OBS! this is a custom validation

  validate :bad_words  # pay attention at validate is in SINGULAR,
  after_validation :generate_slug


  #custom validation ex:
  def bad_words
    title.split(' ').each do |word|

      if BADWORDS.include?(word)
        errors.add(:base, "can't contain bad words")
        break
      end
    end
  end

  #All the functions bellow became 2 different gems (^:^)

  #def total_votes
  #  self.votes.where(vote: true).size - self.votes.where(vote: false).size
  #end

  #def generate_slug
  #  self.slug = self.title.gsub(' ','-').downcase
  #end
  #
  #def to_param
  #  self.slug
  #end




end



# when u use ':title' instead of ':base, check about the css-class that gets created
#for future style-design, it's an error div.

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  # this method does this: @post = Post.find(params[:id])
  before_action :set_post, only: [:show, :edit, :update, :vote ]

  # this method does this:
#  # def require_user
#  if !logged_in?
#    flash[:error] = 'Must be logged in to do that'
#    redirect_to root_path
#  end

  before_action :require_user, only:[:new, :create, :edit, :update, :vote]

  def index
    @posts = Post.all
    myArray = []  #empty array

    respond_to do |format|
      format.html
      format.js {render json: {myArray:  @posts.as_json(only: [:title])}.to_json }
    end


  end

  def show
   # @post = Post.find(params[:id])    we use set_post method
  @comment = Comment.new
  @posts = Post.all

  end

  def new
    @post = Post.new
  end

  def vote
   # Vote.create(voteable: @post, user: current_user, vote: params[:vote])

  #if @post.votes.find_by(user: current_user)
  #    flash[:alert] = 'A user can vote 1 time!'
  #    redirect_to posts_path
  #  else
  #    @post.votes.build(voteable: @post, user: current_user, vote: params[:vote] )
  #    if @post.save
  #      respond_to do |format|
  #        format.html do
  #          flash[:notice] = 'Your vote was counted'
  #          redirect_to root_path
  #        end
  #        format.js
  #      end
  #    else
  #      render 'posts/index'
  #  end
  #  end

    vote_action(@post)

  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
     if @post.save
       flash[:notice] = 'you created a post'
       redirect_to root_path
     else
       render :new
     end

   # binding.pry

  end

  def edit
   # @post = Post.find(params[:id])   we use set_post method
  end

  def update
   #@post = Post.find(params[:id])   we use set_post method
    if @post.update (post_params)
      flash[:notice] = 'This was updated'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def set_post
    @post = Post.find_by slug: params[:id]
  end
  def post_params
    params.require(:post).permit!  #.permit.(:title, :url, :description, :category_ids)
  end




end

app/views/posts/_error_form.html.erb
<% if obj.errors.any?  %>

  <div class="alert alert-error">
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= render 'posts/error_form', obj: @post %>


<!--

New object (posts/new): POST to /posts
Existing obj: PUT or PATCH to /posts/id (1, 2, 3, 4)

-->


<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br/>
  <%= f.label 'Categories' %>
  <%= f.collection_check_boxes :category_ids, @categories, :id, :name do |cb| %>
    <% cb.label(class:'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
  <% end %>
  <p id="btn_form"><%= f.submit (@post.new_record? ? 'Create Post' : 'Update Post'), class: "btn btn-success" %><p>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit a post</h3>

<%= render 'posts/error_form', obj: @post %>

<%= render 'form'  %> <!-- we render _form.html.erb but without the '_' - hypo -->

app/views/posts/index.html.erb
<style type="text/css">


</style>

<h3>Welcome!</h3>

<% @posts.each do |post| %>

  <% if logged_in? %>
    <div class="left well">
      <li> <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
          <i class="icon-chevron-left rotate-up"></i>
        <% end %>
      </li>

      <li>  <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
          <i class="icon-chevron-right rotate-down"></i>

        <% end %>
      </li>
      <li><span class="badge badge-info" id="post_<%=post.id%>_votes"><%= post.total_votes %></span>
      </li>
    </div>
  <% end %>

<div class="right">
<ul>
      <li style="list-style: none;" class="well">
        <p>
          <span class="badge badge-info">
          <% post.categories.each do |i| %>
            <%= i.name %>
          <% end %>
          </span>
        </p>
        <%  if current_user && current_user.admin? %>
          <%= link_to post.title, post_path(post) %> [ <%= link_to 'edit', edit_post_path(post) %> ]
        <% else %>
          <%= link_to post.title, post_path(post) %> <span class="label">no admin?, U can't edit post </span>
        <% end %>

          <p>posted by  <%= post.user.username %> on <%= pretty_date(post.created_at) %></p>

        <span class="badge badge-info"><%= post.comments.length %></span>
        <span style="color: #999;"><%= link_to 'comments inside', post_path(post) %></span>

      </li>



</ul>
</div>
<% end %>

app/views/posts/new.html.erb
<h3>Create a new post</h3>


<%= render 'form'  %> <!-- we render _form.html.erb but without the '_' - hypo -->

app/views/posts/show.html.erb
<div class="">
  <p class="lead"><%= link_to @post.title, fix_url(@post.url) %> </p>
  <p>Description:</p>
  <p class="muted"><%= @post.description %> </p>
</div>

<h3>Comments</h3>

<!-- Validation -->

<%= render 'posts/error_form', obj: @comment %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :body %>
  <p> <%= f.submit 'Create comment', class: 'btn btn-primary' %> </p>
<% end %>

<h3>List of comments</h3>

<% @post.comments.each do |comment|  %>

  <div class="row">
    <div class="well div_left">

      <ul>
        <li class="voting_icon"> <%= link_to vote_post_comment_path(@post, comment, vote: true), method: 'post', remote: true do %>
            <i class="icon-chevron-left rotate-up"></i>
          <% end %>
        </li>

        <li class="voting_icon">  <%= link_to vote_post_comment_path(@post, comment, vote: false), method: 'post', remote: true do %>
            <i class="icon-chevron-right rotate-down"></i>
          <% end %>
        </li>
        <li> <span id="post_<%=@post.id%>_comments_<%=comment.id%>" class="badge badge-info"><%= comment.total_votes %></span>
        </li>
      </ul>
    </div>

    <div class=" div_right well">
      <ul>

          <li><%= comment.body %></li>

      </ul>
    </div>
  </div>

<% end %>

app/views/posts/vote.js.erb
<% if @post_obj %>
$("#post_<%=@post_obj.id%>_comments_<%=@obj.id%>").html("<%=@obj.total_votes%>");

<% else %>
$("#post_<%=@obj.id%>_votes").html("<%= @obj.total_votes %>");
console.log("<%=@obj.total_votes%>");
<% end %>